from django.contrib import admin
from .models import *
admin.site.register(Customer)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(ShippingAddress)
admin.site.register(AboutUs)
admin.site.register(Newsletter)
admin.site.register(Help)
admin.site.register(HomePage)
admin.site.register(ContactForm)
admin.site.register(Mix)
admin.site.register(Photo)
admin.site.register(Category)
admin.site.register(Brand)
admin.site.register(Video)
admin.site.register(AmapianoSignUp)
admin.site.register(Product)
admin.site.register(Type)
admin.site.register(ProductPhoto)
admin.site.register(SpectraTalksSignUp)
